
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\saman\OneDrive\Documents\academic\project\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1400x800")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 800,
    width = 1400,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    700.0,
    400.0,
    image=image_image_1
)

canvas.create_rectangle(
    45.0,
    71.0,
    1354.0,
    730.0,
    fill="#FFFFFF",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=600.0,
    y=495.0,
    width=200.0,
    height=40.0
)

canvas.create_text(
    493.0,
    263.0,
    anchor="nw",
    text="CONGRATULATIONS",
    fill="#000000",
    font=("Ubuntu Bold", 42 * -1)
)

canvas.create_text(
    606.0,
    325.0,
    anchor="nw",
    text="You scored",
    fill="#000000",
    font=("Ubuntu Bold", 36 * -1)
)

canvas.create_text(
    644.0,
    379.0,
    anchor="nw",
    text="9 / 10",
    fill="#009788",
    font=("Ubuntu Bold", 42 * -1)
)
window.resizable(False, False)
window.mainloop()
