
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\saman\OneDrive\Documents\academic\project\build\assets\frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1400x800")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 800,
    width = 1400,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    700.0,
    400.0,
    image=image_image_1
)

canvas.create_rectangle(
    303.0,
    134.0,
    1098.0,
    667.0,
    fill="#FFFFFF",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=601.0,
    y=533.0,
    width=200.0,
    height=40.0
)

canvas.create_text(
    480.0,
    290.0,
    anchor="nw",
    text="#1    Username                99%",
    fill="#000000",
    font=("Ubuntu Bold", 32 * -1)
)

canvas.create_text(
    480.0,
    354.0,
    anchor="nw",
    text="#2    Username                95%",
    fill="#000000",
    font=("Ubuntu Bold", 32 * -1)
)

canvas.create_text(
    480.0,
    412.0,
    anchor="nw",
    text="#3    Username                94%",
    fill="#000000",
    font=("Ubuntu Bold", 32 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    700.0,
    226.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
